### PR TITLE
patch some image link

### PR DESCRIPTION
**Pull request by wiiznokes**
I finally found a way to use git-lfs with readme images :)

### CODE REVIEW

**Comment by edfloreshz** [comment]
Which one should I merge? This or #5?

**Comment by wiiznokes** [comment]
Any of them. It's just the git history which is not the same but the diff are equal

**Comment by edfloreshz** [comment]
There appear to be conflicts, can you resolve them?

**Comment by wiiznokes** [comment]
Maybe try the other one then

**Comment by wiiznokes** [comment]
Oh it also have merge conflict, I think I could resolve it later, I will have to recreate my fork because I modified my main branch

**Comment by edfloreshz** [comment]
Let me see if I can help

**Comment by edfloreshz** [comment]
Closes #5

**Comment by wiiznokes** [comment]
Thanks!

**Pull request merged**
