### PR TITLE
Add `cosmic-ext-applet-system-monitor`

### PR DESCRIPTION
**Pull request by D-Brox**
It's currently a WIP, but I already daily drive it

### CODE REVIEW

**Review by edfloreshz — APPROVED** [review]

**Comment by yochananmarqos** [comment]
@D-Brox Why did you invent a new name? If the `cosmic-ext-applet-` is the new norm, then at least it should be called `cosmic-ext-applet-minimon`. 

By the way, I named my AUR package `minimon-applet-for-cosmic`.

**Comment by D-Brox** [comment]
@yochananmarqos I was inspired by the [GNOME Shell system monitor extension](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet) I used back in gnome-cosmic, so I kept a similar name, and I plan to reach as close to feature parity as possible.

**Comment by yochananmarqos** [comment]
@D-Brox What I meant was, most package names for any GNU / Linux distribution are the same (or close) to the upstream project name.

**Comment by D-Brox** [comment]
@yochananmarqos oh, I think you misunderstood, this isn't based on the minimon applet.

So now there are 2 separate applets for resource monitoring, with different approaches to the same goal.

**Comment by yochananmarqos** [comment]
@D-Brox Wow... Yeah... Oops.

:laughing: 

Sorry about the noise.

By the way, great commit message :grin: 

> And Brox said: Let there be Light

**Comment by D-Brox** [comment]
@yochananmarqos Ye, that has been my default initial commit message for the past few year

**Pull request merged**
