### PR TITLE
Update applets.ron / emoji selector

### PR DESCRIPTION
**Pull request by leb-kuchen**

### CODE REVIEW

**Comment by edfloreshz** [comment]
The image appears to be privately hosted, be sure to include a publicly available image.

**Review by edfloreshz — CHANGES_REQUESTED** [review]

**Comment by leb-kuchen** [comment]
I will be working it on updating the images, once I've finalized my designs.

**Review by edfloreshz — APPROVED** [review]
Looks good! 👍🏼

**Comment by edfloreshz** [comment]
Thanks! 🎉

**Pull request merged**
